version: '3'
services:
  postgres:
    container_name: postgres
    image: ${DOCKER_IMAGE_TAG:-registry.erst.dk/ml-data-images/ml-erst-platform-data-template-image}
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
      - ./support/export-data.sh:/mnt/tools/export-data.sh
      - ./build/postgres:/mnt/data
    environment:
      - POSTGRES_USER=ml
      - POSTGRES_PASSWORD=ml
    ports:
      - 5432:5432
